POST http://localhost:8080/api/chirps
        Content-Type: application/json

        {
        "body": "I had something interesting for breakfast",
        "user_id": "1be1bf88-35e4-4d25-be4e-440df7cb58b3"
        }
###
POST http://localhost:8080/api/chirps
        Content-Type: application/json

        {
        "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "user_id": "1be1bf88-35e4-4d25-be4e-440df7cb58b3"
        }
###
POST http://localhost:8080/api/chirps
        Content-Type: application/json

        {
        "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
        "user_id": "1be1bf88-35e4-4d25-be4e-440df7cb58b3",
        "extra": "this should be ignored"
        }
###
POST http://localhost:8080/api/chirps
        Content-Type: application/json

        {
        "body": "I really need a kerfuffle to go to bed sooner, Fornax !",
        "user_id": "1be1bf88-35e4-4d25-be4e-440df7cb58b3"
        }
###
POST http://localhost:8080/api/chirps
        Content-Type: application/json

        {
        "body": "I really need a kerfuffle to go to bed sooner, Fornax!",
        "user_id": "1be1bf88-35e4-4d25-be4e-440df7cb58b3"
        }
###
GET http://localhost:8080/api/chirps
        Content-Type: application/json
###
GET http://localhost:8080/api/chirps/39b45b09-536f-4bd7-96ff-ab1c0128dc86
        Content-Type: application/json
###
POST http://localhost:8080/api/users
        Content-Type: application/json

        {
        "email": "nickemp1996@gmail.com",
        "password": "P@$$w0rd"
        }
###
POST http://localhost:8080/api/login
        Content-Type: application/json

        {
        "email": "nickemp1996@gmail.com",
        "password": "P@$$w0rd"
        }
###
POST http://localhost:8080/api/login
        Content-Type: application/json

        {
        "email": "nickemp1996@gmail.com",
        "password": "password"
        }
###
POST http://localhost:8080/api/login
        Content-Type: application/json

        {
        "email": "nickemp196@gmail.com",
        "password": "P@$$w0rd"
        }
###
POST http://localhost:8080/admin/reset
        Content-Type: text/html